### ISSUE TITLE
What is the supported linux version

### ISSUE THREAD

**Issue by teto** [mlichvar/linux-tktest#1]
Hi,

I tried using this on my laptop with the latest kernel:

```
make KDIR=~/linux-lkl                                                                                  17:41:31   master 
make -C ~/linux-lkl M=$PWD CFLAGS_timekeeping.o=-I~/linux-lkl/kernel/time timekeeping.o
make[1]: Entering directory '/home/teto/linux-lkl'
  CC      /home/teto/linux-tktest/timekeeping.o
/home/teto/linux-tktest/timekeeping.c:27:27: fatal error: tick-internal.h: Aucun fichier ou dossier de ce type
compilation terminated.
scripts/Makefile.build:258: recipe for target '/home/teto/linux-tktest/timekeeping.o' failed
make[2]: *** [/home/teto/linux-tktest/timekeeping.o] Error 1
Makefile:1527: recipe for target 'timekeeping.o' failed
make[1]: *** [timekeeping.o] Error 2
make[1]: Leaving directory '/home/teto/linux-lkl'
Makefile:16: recipe for target 'timekeeping.o' failed
make: *** [timekeeping.o] Error 2
```

Which kernel version should I use then ? (maybe worth adding in README.md too)

**Comment by mlichvar** [comment]
This could be a problem with the kernel configuration. Can you try `make defconfig` and `make modules_prepare` before building tktest?

The linux tree from the date of the last tktest commit should work, but current tree still seems to be working for me.

**Comment by walbon** [comment]
What are the full steps to build it? Just make  defconfig and modules_prepare?
So, I have worked with Kernel version 4.14 and there is a conflict with set_normalized_timespec from linux/time.h then the timekeeping.c from kernel was not built.

**Comment by walbon** [comment]
# make
cc -O2 -Wall -g -c main.c
make -C /root/linux-tktest/linux M=$PWD CFLAGS_missing.o=-Wno-strict-prototypes missing.o
cc -O2 -Wall -g -c regress.c
ln -s /root/linux-tktest/linux/kernel/time/timekeeping.c timekeeping.c
make -C /root/linux-tktest/linux M=$PWD CFLAGS_tk_test.o=-Wno-strict-prototypes tk_test.o
make -C /root/linux-tktest/linux M=$PWD CFLAGS_timekeeping.o=-I/root/linux-tktest/linux/kernel/time timekeeping.o
make[1]: Entering directory `/root/powerpc'
make[1]: Entering directory `/root/powerpc'
make[1]: Entering directory `/root/powerpc'
  CC      /root/linux-tktest/missing.o
  CC      /root/linux-tktest/tk_test.o
  CC      /root/linux-tktest/timekeeping.o
make[1]: Leaving directory `/root/powerpc'
make[1]: Leaving directory `/root/powerpc'
make[1]: Leaving directory `/root/powerpc'
cc -O2 -Wall -g -o tk_test main.o missing.o regress.o timekeeping.o tk_test.o -lm
timekeeping.o: In function `tk_set_wall_to_mono':
timekeeping.c:(.text+0x1018): undefined reference to `set_normalized_timespec64'
timekeeping.c:(.text+0x1070): undefined reference to `set_normalized_timespec64'
timekeeping.o: In function `get_monotonic_coarse64':
(.text+0x1178): undefined reference to `set_normalized_timespec64'
timekeeping.o: In function `do_settimeofday64':
(.text+0x1b98): undefined reference to `set_normalized_timespec64'
timekeeping.o: In function `__timekeeping_inject_sleeptime.constprop.8':
timekeeping.c:(.text+0x20c4): undefined reference to `set_normalized_timespec64'
timekeeping.o:timekeeping.c:(.text+0x21fc): more undefined references to `set_normalized_timespec64' follow
timekeeping.o: In function `do_adjtimex':
(.text+0x38ac): undefined reference to `capable'
timekeeping.o: In function `do_adjtimex':
(.text+0x3904): undefined reference to `capable'
timekeeping.o: In function `do_adjtimex':
(.text+0x3974): undefined reference to `capable'
timekeeping.o: In function `timekeeping_init':
(.init.text+0x204): undefined reference to `set_normalized_timespec64'
timekeeping.o:(.toc+0x0): undefined reference to `sys_tz'
collect2: error: ld returned 1 exit status
make: *** [tk_test] Error 1
#

**Comment by mlichvar** [comment]
Unfortunately it breaks frequently as the kernel code is changing. I've pushed a fix to make it work with the current code. Please pull and try again.

**Comment by teto** [comment]
thanks closing this
